version: '3'
services:
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        container_name: biopatternsg_mysql
        environment:
            MYSQL_ROOT_PASSWORD: biopatternsg2021
        ports:
            - 12600:3306
        volumes:
            - ./mysql/:/var/lib/mysql
    mongo:
        image: mongo:4.4.6-bionic
        container_name: biopatternsg_mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: biopatternsg
            MONGO_INITDB_ROOT_PASSWORD: biopatternsg2021
        ports:
            - 12500:27017
        volumes:
            - ./mongo/:/etc/mongo
    zookeeper:
        container_name: biopatternsg_zookeeper
        image: zookeeper:3.7
    kafka:
        container_name: biopatternsg_kafka
        image: wurstmeister/kafka:2.13-2.7.1
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            ZK_SERVER: zookeeper:2181
            ADVERTISED_HOST: localhost
            CONSUMER_THREADS: 5
            BROKER_ID: 1
            ADVERTISED_PORT: 9092
volumes:
    mysql: {}
    mongo: {}
